export {LoginPage} from './login'
export {RegisterPage} from './register'
export {ChatsPage} from './chats'
export {NavigatePage} from './navigate'
export {InfoPage} from './info'
export {ProfilePage} from './profile'
