export {SigninPage} from './signin'
export {SignupPage as RegisterPage} from './signup'
export {ChatsPage} from './chats'
export {NavigatePage} from './navigate'
export {InfoPage} from './info'
export {ProfilePage} from './profile'
